// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFauBrMUw8RbaXxx_inV_BgBC9_9d6aPk',
    appId: '1:644386846756:web:29a5a0b554a54ae69300b1',
    messagingSenderId: '644386846756',
    projectId: 'appdev-a0da7',
    authDomain: 'appdev-a0da7.firebaseapp.com',
    storageBucket: 'appdev-a0da7.appspot.com',
    measurementId: 'G-B41TLQ3G80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBegHaS5cjmQ-JXuJzFZxjKzmMSDb4uaGI',
    appId: '1:644386846756:android:82626d61f47ed4099300b1',
    messagingSenderId: '644386846756',
    projectId: 'appdev-a0da7',
    storageBucket: 'appdev-a0da7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRVFuSOO_g6Dccu1CxWmbqx6sib8dcL5Y',
    appId: '1:644386846756:ios:7436c3bab63aa0e09300b1',
    messagingSenderId: '644386846756',
    projectId: 'appdev-a0da7',
    storageBucket: 'appdev-a0da7.appspot.com',
    iosBundleId: 'com.example.quickgrocerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRVFuSOO_g6Dccu1CxWmbqx6sib8dcL5Y',
    appId: '1:644386846756:ios:1140df4937f80caf9300b1',
    messagingSenderId: '644386846756',
    projectId: 'appdev-a0da7',
    storageBucket: 'appdev-a0da7.appspot.com',
    iosBundleId: 'com.example.quickgrocerApplication.RunnerTests',
  );
}
